import React, { useState, useEffect, useRef } from 'react';
import { LooksAnalysis } from '../types';
import { Button } from './Button';
import { CrownLogo } from './CrownLogo';
import { LOADING_MESSAGES } from '../utils/analysisUtils';
import { useUser } from '../contexts/UserContext';
import { useAIGeneration } from '../hooks/useAIGeneration';
import { getHistory, simulateInviteAccepted } from '../services/historyService';
import { STRIPE_LINKS, PRICING } from '../config';
import { SEOHead } from './SEOHead';

// Components
import { PaywallModal, TopUpModal } from './PremiumModals';
import { ArchetypeVisualizer } from './ArchetypeVisualizer';
import { AnalysisHeader } from './analysis/AnalysisHeader';
import { AnalysisGrid } from './analysis/AnalysisGrid';
import { HardmaxxingSection } from './analysis/HardmaxxingSection';
import { StarterKit } from './analysis/StarterKit';
import { StyleVisionBoard } from './analysis/StyleVisionBoard';
import { ImageViewer } from './ui/ImageViewer';

interface AnalysisResultProps {
  analysis: LooksAnalysis;
  imageData: string | null;
  onRetake: () => void;
  scanId?: string;
  onOpenCoach: () => void;
}

export const AnalysisResult: React.FC<AnalysisResultProps> = ({ analysis, imageData, onRetake, scanId, onOpenCoach }) => {
  const { user, unlockPremium, addCredits, checkQuota, refreshUser } = useUser();
  const { generateAsset, isGenerating, activeOperation } = useAIGeneration(scanId);

  // --- UI State ---
  const [showPaywall, setShowPaywall] = useState(false);
  const [showTopUp, setShowTopUp] = useState(false);
  const [processingPayment, setProcessingPayment] = useState(false);
  const [loadingMessageIdx, setLoadingMessageIdx] = useState(0);
  const [fullScreenImage, setFullScreenImage] = useState<string | null>(null);
  const [shareSuccess, setShareSuccess] = useState(false);

  // --- Asset State ---
  const [optimalImages, setOptimalImages] = useState<{ [key: string]: string }>({});
  const [styleImages, setStyleImages] = useState<{ [key: string]: string }>({});
  const [procedureImages, setProcedureImages] = useState<{ [key: string]: string }>({});
  
  // --- Feature State ---
  const [activeArchetype, setActiveArchetype] = useState<'softmax' | 'hardmaxx' | 'titan' | 'icon'>('softmax');
  const [toggledProcedures, setToggledProcedures] = useState<{ [key: string]: boolean }>({}); 
  const [comparisonModal, setComparisonModal] = useState<{ before: string, after: string } | null>(null);

  // --- Custom Uploads ---
  const [customStyleImage, setCustomStyleImage] = useState<string | null>(null);
  const [customSurgeryImage, setCustomSurgeryImage] = useState<string | null>(null);

  const hasAutoGeneratedRef = useRef(false);

  // 1. Rehydrate Assets from History
  useEffect(() => {
    if (scanId) {
        const history = getHistory();
        const item = history.find(h => h.id === scanId);
        if (item && item.assets) {
            const newOptimal: any = {};
            const newStyle: any = {};
            const newProcs: any = {};
            Object.keys(item.assets).forEach(key => {
                if (key.startsWith('optimal_')) newOptimal[key.replace('optimal_', '')] = item.assets![key];
                if (key.startsWith('style_')) newStyle[key.replace('style_', '')] = item.assets![key];
                if (key.startsWith('proc_')) newProcs[key.replace('proc_', '')] = item.assets![key];
            });
            setOptimalImages(newOptimal);
            setStyleImages(newStyle);
            setProcedureImages(newProcs);
        }
    }
  }, [scanId]);

  // 2. Cycling Loading Messages
  useEffect(() => {
      let interval: any;
      if (isGenerating) {
          interval = setInterval(() => setLoadingMessageIdx(p => (p + 1) % LOADING_MESSAGES.length), 1500);
      } else {
          setLoadingMessageIdx(0);
      }
      return () => clearInterval(interval);
  }, [isGenerating]);

  // 3. Auto-Generate Softmaxx Archetype
  useEffect(() => {
    if (imageData && !optimalImages['softmax'] && !isGenerating && !hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        handleGenerateOptimal('softmax');
    }
  }, [imageData, optimalImages]); 

  // --- Handlers ---

  const handleShare = async () => {
    if (!user) return;
    const shareText = `I scored ${analysis.overallScore.toFixed(1)}/10 on LooksMaxx King! Use my code ${user.referralCode} to see your ascension. 👑 https://looksmaxx.ai`;
    
    if (navigator.share) {
        try {
            await navigator.share({ title: 'My LooksMaxx Rating', text: shareText, url: 'https://looksmaxx.ai' });
            simulateInviteAccepted();
            setShareSuccess(true);
            refreshUser();
            setTimeout(() => setShareSuccess(false), 3000);
        } catch (e) {
            console.error(e);
        }
    } else {
        navigator.clipboard.writeText(shareText);
        simulateInviteAccepted();
        setShareSuccess(true);
        refreshUser();
        setTimeout(() => setShareSuccess(false), 3000);
    }
  };

  const handleSimulatePayment = (type: 'premium' | 'credits') => {
      setProcessingPayment(true);
      const url = type === 'premium' ? STRIPE_LINKS.PREMIUM_UNLOCK : STRIPE_LINKS.CREDITS_TOPUP;
      window.open(url, '_blank');
      setTimeout(() => {
          if (type === 'premium') { unlockPremium(); setShowPaywall(false); } 
          else { addCredits(PRICING.CREDIT_PACK_AMOUNT); setShowTopUp(false); }
          setProcessingPayment(false);
      }, 8000);
  };

  const handleCustomUpload = (e: React.ChangeEvent<HTMLInputElement>, setFunc: (s: string) => void) => {
      const file = e.target.files?.[0];
      if (file) {
          const reader = new FileReader();
          reader.onload = (ev) => ev.target?.result && setFunc(ev.target.result as string);
          reader.readAsDataURL(file);
      }
  }

  const checkAccess = (key: string): boolean => {
      const status = checkQuota(key);
      if (!status.allowed) {
          if (status.reason === 'premium_lock') setShowPaywall(true);
          else setShowTopUp(true);
          return false;
      }
      return true;
  };

  const handleGenerateOptimal = async (archetype: 'softmax' | 'hardmaxx' | 'titan' | 'icon') => {
    if (!imageData) return;
    setActiveArchetype(archetype);
    if (optimalImages[archetype]) return;
    if (!checkAccess(archetype)) return;
    const img = await generateAsset('optimal', archetype, imageData);
    if (img) setOptimalImages(prev => ({ ...prev, [archetype]: img }));
  };

  const handleGenerateStyle = async (category: 'hair' | 'fashion' | 'grooming') => {
      if (styleImages[category]) return;
      const source = customStyleImage || imageData;
      if (!source) return;
      if (!checkAccess('style')) return;
      const img = await generateAsset('style', category, source);
      if (img) setStyleImages(prev => ({...prev, [category]: img}));
  };

  const handleGenerateProcedure = async (procName: string, description: string) => {
    const source = customSurgeryImage || imageData;
    if (!source) return;
    if (!checkAccess('surgery')) return;
    const img = await generateAsset('surgery', procName, source, { description });
    if (img) {
        setProcedureImages(prev => ({...prev, [procName]: img}));
        setToggledProcedures(prev => ({...prev, [procName]: true}));
    }
  };

  const starterProducts = [
    ...(analysis.skinAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'SKIN'}))),
    ...(analysis.hairAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'HAIR'}))),
    ...(analysis.eyeAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'EYES'}))),
    ...(analysis.hardmaxxing && analysis.hardmaxxing.length > 0 ? [{ name: "Mastic Gum", reason: "For Jawline", searchQuery: "Mastic Gum", tag: "JAW" }] : []),
  ].slice(0, 6);

  const isPremiumUnlocked = user?.isPremium || false;

  return (
    <div className="w-full max-w-7xl mx-auto flex flex-col gap-6 animate-fade-in pb-20 px-4 sm:px-6 lg:px-8">
      <SEOHead 
        title={`Your AI Face Analysis Score: ${analysis.overallScore.toFixed(1)}/10`} 
        description={`My facial aesthetic score is ${analysis.overallScore.toFixed(1)}.`}
      />

      {showPaywall && <PaywallModal onClose={() => setShowPaywall(false)} onPurchase={() => handleSimulatePayment('premium')} isProcessing={processingPayment} />}
      {showTopUp && <TopUpModal onClose={() => setShowTopUp(false)} onPurchase={() => handleSimulatePayment('credits')} isProcessing={processingPayment} />}
      
      <ImageViewer src={fullScreenImage} onClose={() => setFullScreenImage(null)} />

      {comparisonModal && (
          <div className="fixed inset-0 z-[70] bg-black/95 flex items-center justify-center p-2 md:p-8 animate-fade-in">
               <div className="w-full max-w-6xl h-full flex flex-col">
                  <div className="flex justify-between items-center mb-4 px-2">
                       <h3 className="text-white font-black text-lg uppercase tracking-widest italic">Anatomical Comparison</h3>
                       <button onClick={() => setComparisonModal(null)} className="bg-zinc-800 text-white px-6 py-2 rounded-full font-bold text-xs uppercase">Close</button>
                  </div>
                  <div className="flex-grow flex flex-col md:flex-row gap-2 md:gap-4 h-[80vh]">
                      <div className="flex-1 relative rounded-3xl overflow-hidden border border-zinc-800"><img src={comparisonModal.before} className="w-full h-full object-cover" alt="Before" /><div className="absolute top-4 left-4 bg-black/70 text-white px-3 py-1 rounded text-[10px] font-black uppercase tracking-widest">Base</div></div>
                      <div className="flex-1 relative rounded-3xl overflow-hidden border border-emerald-500/30"><img src={comparisonModal.after} className="w-full h-full object-cover" alt="After" /><div className="absolute top-4 left-4 bg-emerald-600/90 text-white px-3 py-1 rounded text-[10px] font-black uppercase tracking-widest">Simulation</div></div>
                  </div>
              </div>
          </div>
      )}

      <AnalysisHeader 
        analysis={analysis} 
        imageData={imageData} 
        softmaxImage={optimalImages['softmax']} 
        hardmaxxImage={optimalImages['hardmaxx']}
        isGenerating={isGenerating}
        activeOperation={activeOperation}
        onRetake={onRetake} 
        onFullScreen={setFullScreenImage}
        onGenerate={handleGenerateOptimal}
      />

      <div className="flex justify-center -mt-8 relative z-20">
          <button 
            onClick={handleShare}
            className={`px-8 py-4 rounded-full font-black uppercase tracking-widest shadow-2xl transition-all hover:scale-105 active:scale-95 flex items-center gap-3 border-2 ${shareSuccess ? 'bg-emerald-500 border-emerald-400 text-white' : 'bg-black dark:bg-white text-white dark:text-black border-zinc-800 dark:border-zinc-200'}`}
          >
              {shareSuccess ? (
                  <>
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                    ROYALTY REWARDED
                  </>
              ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M7.217 10.907a2.25 2.25 0 100 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186l9.566-5.314m-9.566 7.5l9.566 5.314m0 0a2.25 2.25 0 103.935 2.186 2.25 2.25 0 00-3.935-2.186zm0-12.814a2.25 2.25 0 103.933-2.185 2.25 2.25 0 00-3.933 2.185z" /></svg>
                    SHARE FOR 1 CREDIT
                  </>
              )}
          </button>
      </div>

      <StarterKit products={starterProducts} />

       <div className="bg-gradient-to-br from-amber-600 to-amber-800 rounded-3xl p-6 shadow-2xl relative overflow-hidden cursor-pointer flex flex-col md:flex-row items-center gap-6 group hover:scale-[1.01] transition-transform" onClick={onOpenCoach}>
             <div className="flex-shrink-0 p-4 bg-amber-500/10 rounded-full border border-amber-500/30 group-hover:bg-amber-500/20 transition-colors"><CrownLogo className="w-12 h-12 text-amber-500" /></div>
             <div className="flex-grow text-center md:text-left"><h3 className="text-xl font-black text-white uppercase italic">Execution Is Everything</h3><p className="text-zinc-200 text-sm">Follow your personalized Daily Protocol to reach peak aesthetics.</p></div>
             <Button onClick={(e) => { e.stopPropagation(); onOpenCoach(); }} className="bg-amber-500 text-black border-none px-10 font-black italic tracking-widest uppercase">Start Protocol</Button>
        </div>

      <ArchetypeVisualizer 
        activeArchetype={activeArchetype}
        isPremiumUnlocked={isPremiumUnlocked}
        isGenerating={isGenerating && ['softmax', 'hardmaxx', 'titan', 'icon'].includes(activeOperation || '')}
        currentImage={optimalImages[activeArchetype]}
        onGenerate={handleGenerateOptimal}
        onTriggerPaywall={() => setShowPaywall(true)}
        onFullScreen={setFullScreenImage}
        loadingMessage={LOADING_MESSAGES[loadingMessageIdx]}
      />

      <StyleVisionBoard 
        isPremiumUnlocked={isPremiumUnlocked}
        styleImages={styleImages}
        isGenerating={isGenerating && ['hair', 'fashion', 'grooming'].includes(activeOperation || '')}
        activeOperation={activeOperation}
        onGenerate={handleGenerateStyle}
        onTriggerPaywall={() => setShowPaywall(true)}
        onFullScreen={setFullScreenImage}
        onUpload={(e) => handleCustomUpload(e, setCustomStyleImage)}
      />

      <HardmaxxingSection 
        analysis={analysis} 
        isPremiumUnlocked={isPremiumUnlocked} 
        onUnlock={() => setShowPaywall(true)}
        onGenerate={handleGenerateProcedure}
        procedureImages={procedureImages}
        loadingProcedure={isGenerating && !['softmax','hardmaxx','titan','icon','hair','fashion','grooming'].includes(activeOperation || '') ? activeOperation : null}
        toggleView={(name) => setToggledProcedures(prev => ({ ...prev, [name]: !prev[name] }))}
        toggledState={toggledProcedures}
        onCompare={(after) => imageData && setComparisonModal({ before: imageData, after })}
        imageData={imageData}
        customImage={customSurgeryImage}
        onUpload={(e) => handleCustomUpload(e, setCustomSurgeryImage)}
      />

      <AnalysisGrid analysis={analysis} />
    </div>
  );
};