
import React, { useState, useEffect, useRef } from 'react';
import { LooksAnalysis } from '../types';
import { Button } from './Button';
import { CrownLogo } from './CrownLogo';
import { AMAZON_TAG } from '../config';
import { generateOptimalImage, generateStyleInspiration, generateProcedureSimulation } from '../services/geminiService';
import { checkCanGenerate, incrementUsage, addCredits, unlockPremium, saveGeneratedAsset, getHistory } from '../services/historyService';
import { PaywallModal, TopUpModal } from './PremiumModals';
import { ArchetypeVisualizer } from './ArchetypeVisualizer';

const LockIcon: React.FC<{ className?: string }> = ({ className = "w-6 h-6" }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className}>
        <path fillRule="evenodd" d="M12 1.5a5.25 5.25 0 00-5.25 5.25v3a3 3 0 00-3 3v6.75a3 3 0 003 3h10.5a3 3 0 003-3v-6.75a3 3 0 00-3-3v-3c0-2.9-2.35-5.25-5.25-5.25zm3.75 8.25v-3a3.75 3.75 0 10-7.5 0v3h7.5z" clipRule="evenodd" />
    </svg>
);

interface AnalysisResultProps {
  analysis: LooksAnalysis;
  imageData: string | null;
  onRetake: () => void;
  scanId?: string;
  onOpenCoach: () => void;
}

const LOADING_MESSAGES = [
    "Consulting the Royal Physicians...",
    "Measuring Golden Ratio Deviation...",
    "Judging Facial Symmetry...",
    "Rendering Ascension Preview...",
    "Accessing the King's Vault...",
    "Simulating Surgical Outcome...",
];

export const AnalysisResult: React.FC<AnalysisResultProps> = ({ analysis, imageData, onRetake, scanId, onOpenCoach }) => {
  // Premium State with Persistence
  const [isPremiumUnlocked, setIsPremiumUnlocked] = useState(() => {
    if (typeof window !== 'undefined') {
        return localStorage.getItem('looksmax_premium_unlocked') === 'true';
    }
    return false;
  });
  
  const [showPaywall, setShowPaywall] = useState(false);
  const [showTopUp, setShowTopUp] = useState(false);
  const [processingPayment, setProcessingPayment] = useState(false);

  // Optimal Image State
  const [optimalImages, setOptimalImages] = useState<{ [key: string]: string }>({});
  const [activeArchetype, setActiveArchetype] = useState<'prime' | 'titan' | 'icon'>('prime');
  const [isGenerating, setIsGenerating] = useState(false);
  const [loadingMessageIdx, setLoadingMessageIdx] = useState(0);
  
  // Style Inspiration State
  const [styleImages, setStyleImages] = useState<{ [key: string]: string }>({});
  const [loadingStyle, setLoadingStyle] = useState<string | null>(null);

  // Procedure Simulation State
  const [procedureImages, setProcedureImages] = useState<{ [key: string]: string }>({});
  const [loadingProcedure, setLoadingProcedure] = useState<string | null>(null);
  const [toggledProcedures, setToggledProcedures] = useState<{ [key: string]: boolean }>({}); 

  // New Photo Upload Refs
  const styleUploadRef = useRef<HTMLInputElement>(null);
  const surgeryUploadRef = useRef<HTMLInputElement>(null);
  const [customStyleImage, setCustomStyleImage] = useState<string | null>(null);
  const [customSurgeryImage, setCustomSurgeryImage] = useState<string | null>(null);

  // Full Screen Image State
  const [fullScreenImage, setFullScreenImage] = useState<string | null>(null);
  const [comparisonModal, setComparisonModal] = useState<{ before: string, after: string } | null>(null);

  const hasAutoGeneratedRef = useRef(false);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;
    if (scanId) {
        const history = getHistory();
        const item = history.find(h => h.id === scanId);
        if (item && item.assets) {
            const newOptimal: any = {};
            const newStyle: any = {};
            const newProcs: any = {};
            Object.keys(item.assets).forEach(key => {
                if (key.startsWith('optimal_')) newOptimal[key.replace('optimal_', '')] = item.assets![key];
                if (key.startsWith('style_')) newStyle[key.replace('style_', '')] = item.assets![key];
                if (key.startsWith('proc_')) newProcs[key.replace('proc_', '')] = item.assets![key];
            });
            setOptimalImages(prev => ({...prev, ...newOptimal}));
            setStyleImages(prev => ({...prev, ...newStyle}));
            setProcedureImages(prev => ({...prev, ...newProcs}));
        }
    }
    return () => { isMountedRef.current = false; };
  }, [scanId]);

  useEffect(() => {
      let interval: any;
      if (isGenerating || loadingStyle || loadingProcedure) {
          interval = setInterval(() => {
              setLoadingMessageIdx(prev => (prev + 1) % LOADING_MESSAGES.length);
          }, 1500);
      } else {
          setLoadingMessageIdx(0);
      }
      return () => clearInterval(interval);
  }, [isGenerating, loadingStyle, loadingProcedure]);

  useEffect(() => {
    if (imageData && !optimalImages['prime'] && !isGenerating && !hasAutoGeneratedRef.current && !optimalImages['prime']) {
        hasAutoGeneratedRef.current = true;
        const timer = setTimeout(() => {
            if (isMountedRef.current) handleGenerateOptimal('prime');
        }, 100);
        return () => clearTimeout(timer);
    }
  }, [imageData]); 

  const handleSimulatePayment = () => {
      setProcessingPayment(true);
      setTimeout(() => {
          setIsPremiumUnlocked(true);
          unlockPremium();
          setProcessingPayment(false);
          setShowPaywall(false);
          if (typeof navigator !== 'undefined' && navigator.vibrate) navigator.vibrate([100, 50, 100]);
      }, 2000);
  };

  const handleTopUp = () => {
      setProcessingPayment(true);
      setTimeout(() => {
          addCredits(25);
          setProcessingPayment(false);
          setShowTopUp(false);
          alert("25 Generations Added!");
      }, 2000);
  }

  const triggerPaywall = () => {
      if (typeof navigator !== 'undefined' && navigator.vibrate) navigator.vibrate(50);
      setShowPaywall(true);
  };

  const handleSectionUpload = (e: React.ChangeEvent<HTMLInputElement>, setFunc: (s: string) => void) => {
      const file = e.target.files?.[0];
      if (file) {
          const reader = new FileReader();
          reader.onload = (ev) => {
              if (ev.target?.result) setFunc(ev.target.result as string);
          }
          reader.readAsDataURL(file);
      }
  }

  const getAmazonLink = (query: string) => {
    return `https://www.amazon.com/s?k=${encodeURIComponent(query)}&tag=${AMAZON_TAG}`;
  };

  const handleGenerateOptimal = async (archetype: 'prime' | 'titan' | 'icon') => {
    if (!imageData) return;
    if (archetype === 'icon' && !isPremiumUnlocked) {
        triggerPaywall();
        return;
    }
    setActiveArchetype(archetype);
    if (optimalImages[archetype]) return;

    if (archetype === 'icon') {
        const check = checkCanGenerate('optimal');
        if (!check.allowed) {
            setShowTopUp(true);
            return;
        }
    }

    setIsGenerating(true);
    try {
      const img = await generateOptimalImage(imageData, archetype);
      if (isMountedRef.current) {
          setOptimalImages(prev => ({ ...prev, [archetype]: img }));
          if (archetype === 'icon') {
              incrementUsage('optimal');
              if (scanId) saveGeneratedAsset(scanId, `optimal_${archetype}`, img);
          }
          if (typeof navigator !== 'undefined' && navigator.vibrate) navigator.vibrate(50);
      }
    } catch (error) {
      console.error(error);
    } finally {
      if (isMountedRef.current) setIsGenerating(false);
    }
  };

  const handleGenerateStyle = async (category: 'hair' | 'fashion' | 'grooming') => {
      if (!isPremiumUnlocked) {
          triggerPaywall();
          return;
      }
      const usage = checkCanGenerate('style');
      if (!usage.allowed) {
          setShowTopUp(true);
          return;
      }
      const sourceImage = customStyleImage || imageData;
      if (!sourceImage || styleImages[category]) return;
      setLoadingStyle(category);
      try {
          const img = await generateStyleInspiration(sourceImage, category);
          if (isMountedRef.current) {
              setStyleImages(prev => ({...prev, [category]: img}));
              incrementUsage('style');
              if (scanId) saveGeneratedAsset(scanId, `style_${category}`, img);
          }
      } catch (error) {
          console.error(error);
      } finally {
          if (isMountedRef.current) setLoadingStyle(null);
      }
  };

  const handleGenerateProcedure = async (procName: string, description: string) => {
    if (!isPremiumUnlocked) {
        triggerPaywall();
        return;
    }
    const usage = checkCanGenerate('surgery');
    if (!usage.allowed) {
        setShowTopUp(true);
        return;
    }
    const sourceImage = customSurgeryImage || imageData;
    if (!sourceImage) return;
    setLoadingProcedure(procName);
    try {
        const img = await generateProcedureSimulation(sourceImage, procName, description);
        if (isMountedRef.current) {
            setProcedureImages(prev => ({...prev, [procName]: img}));
            incrementUsage('surgery');
            if (scanId) saveGeneratedAsset(scanId, `proc_${procName}`, img);
        }
    } catch (error) {
        console.error(error);
    } finally {
        if (isMountedRef.current) setLoadingProcedure(null);
    }
  };

  const toggleProcedureView = (procName: string) => {
      setToggledProcedures(prev => ({ ...prev, [procName]: !prev[procName] }));
  };

  const starterKit = [
    ...(analysis.skinAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'SKIN'}))),
    ...(analysis.hairAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'HAIR'}))),
    ...(analysis.eyeAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'EYES'}))),
    ...(analysis.hardmaxxing && analysis.hardmaxxing.length > 0 ? [{ name: "Mastic Gum", reason: "For Jawline", searchQuery: "Mastic Gum", tag: "JAW" }] : []),
    ...(analysis.beardAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'BEARD'}))),
    ...(analysis.skinAnalysis.products.slice(1, 2).map(p => ({...p, tag: 'SKIN'})))
  ].slice(0, 6);

  const getScoreColor = (score: number) => {
    if (score >= 9.0) return "text-amber-500 dark:text-amber-400 drop-shadow-[0_0_10px_rgba(251,191,36,0.5)]";
    if (score >= 8.0) return "text-emerald-500 dark:text-emerald-400";
    if (score >= 6.0) return "text-blue-500 dark:text-blue-400";
    if (score >= 4.0) return "text-yellow-500 dark:text-yellow-400";
    return "text-red-500 dark:text-red-400";
  };
  
  const getTier = (score: number) => {
      if (score >= 9.0) return { label: "ROYALTY", color: "from-amber-300 via-yellow-400 to-amber-600 text-amber-950" };
      if (score >= 8.0) return { label: "NOBLE", color: "from-emerald-400 to-emerald-600 text-white" };
      if (score >= 6.5) return { label: "KNIGHT", color: "from-blue-400 to-blue-600 text-white" };
      if (score >= 5.0) return { label: "COMMONER", color: "from-zinc-400 to-zinc-600 text-white" };
      return { label: "PEASANT", color: "from-gray-500 to-gray-700 text-white" };
  };
  
  const tier = getTier(analysis.overallScore);

  return (
    <div className="w-full max-w-7xl mx-auto flex flex-col gap-4 md:gap-6 animate-fade-in pb-20 px-4 sm:px-6 lg:px-8">
      
      {showPaywall && (
        <PaywallModal onClose={() => setShowPaywall(false)} onPurchase={handleSimulatePayment} isProcessing={processingPayment} />
      )}

      {showTopUp && (
        <TopUpModal onClose={() => setShowTopUp(false)} onPurchase={handleTopUp} isProcessing={processingPayment} />
      )}

      {fullScreenImage && (
        <div 
            className="fixed inset-0 z-[60] bg-black/95 backdrop-blur-xl flex items-center justify-center p-4 animate-fade-in cursor-zoom-out"
            onClick={() => setFullScreenImage(null)}
        >
            <img src={fullScreenImage} alt="Full Screen" className="max-w-full max-h-[90vh] object-contain rounded-lg" />
            <button className="absolute top-4 right-4 text-white"><svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button>
        </div>
      )}
      
      {comparisonModal && (
          <div className="fixed inset-0 z-[70] bg-black/95 flex flex-col items-center justify-center p-2 md:p-8 animate-fade-in">
               <div className="w-full max-w-6xl h-full flex flex-col">
                  <div className="flex justify-between items-center mb-4 px-2">
                       <h3 className="text-white font-bold text-lg uppercase tracking-widest">Comparison</h3>
                       <button onClick={() => setComparisonModal(null)} className="bg-zinc-800 hover:bg-zinc-700 text-white px-4 py-2 rounded-full font-bold text-sm">Close</button>
                  </div>
                  <div className="flex-grow flex flex-col md:flex-row gap-2 md:gap-4 h-[80vh]">
                      <div className="flex-1 relative rounded-xl overflow-hidden border border-zinc-800">
                           <img src={comparisonModal.before} className="w-full h-full object-cover" alt="Before" />
                           <div className="absolute top-4 left-4 bg-black/70 text-white px-3 py-1 rounded text-xs font-bold uppercase tracking-wider">Before</div>
                      </div>
                      <div className="flex-1 relative rounded-xl overflow-hidden border border-zinc-800">
                           <img src={comparisonModal.after} className="w-full h-full object-cover" alt="After" />
                           <div className="absolute top-4 left-4 bg-emerald-600/90 text-white px-3 py-1 rounded text-xs font-bold uppercase tracking-wider">Simulation</div>
                      </div>
                  </div>
              </div>
          </div>
      )}

      {/* Header Card */}
      <div className="bg-white/90 dark:bg-zinc-900/90 backdrop-blur-xl rounded-[2rem] border border-gray-200 dark:border-zinc-800 overflow-hidden shadow-2xl relative">
        <div className={`absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r ${tier.color.split(' ')[0]} ${tier.color.split(' ')[2]}`}></div>
        <div className="absolute -top-10 -right-10 text-gray-100 dark:text-zinc-800 opacity-30 transform rotate-12 pointer-events-none">
            <CrownLogo className="w-64 h-64 md:w-96 md:h-96" />
        </div>

        <div className="relative p-6 md:p-10 z-10">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 items-center justify-center mb-10">
                <div className="flex flex-col items-center">
                    <div className="w-32 h-32 md:w-48 md:h-48 rounded-full p-1 bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 shadow-xl relative overflow-hidden flex items-center justify-center mb-6">
                        <img src={imageData || ''} alt="Current" className="w-full h-full object-cover rounded-full" />
                         <div className={`absolute -bottom-2 left-1/2 -translate-x-1/2 bg-gradient-to-br ${tier.color} text-[10px] md:text-xs font-black px-3 py-1 rounded-full shadow-lg uppercase tracking-wider border-2 border-white dark:border-black whitespace-nowrap z-20`}>
                            {tier.label}
                        </div>
                    </div>
                    <div className="text-center">
                        <h2 className="text-gray-500 dark:text-zinc-500 uppercase tracking-[0.2em] text-[10px] md:text-xs font-bold mb-1">Current Reality</h2>
                        <div className={`text-5xl md:text-7xl font-black tracking-tighter ${getScoreColor(analysis.overallScore)}`}>{analysis.overallScore}</div>
                    </div>
                </div>

                <div className="hidden md:flex flex-col items-center justify-center absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 opacity-20">
                     <span className="text-xs font-black">VS</span>
                </div>

                <div className="flex flex-col items-center">
                     <div className="w-32 h-32 md:w-48 md:h-48 rounded-full p-1 bg-gradient-to-br from-amber-200 via-amber-400 to-amber-600 shadow-[0_0_30px_rgba(251,191,36,0.4)] relative overflow-hidden mb-6">
                             <div className="w-full h-full bg-black rounded-full overflow-hidden relative flex items-center justify-center">
                                {optimalImages['prime'] ? (
                                    <img src={optimalImages['prime']} alt="Potential" className="w-full h-full object-cover object-center animate-fade-in" />
                                ) : (
                                    <div className="w-8 h-8 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                                )}
                             </div>
                        <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 bg-amber-500 text-black text-[10px] md:text-xs font-black px-3 py-1 rounded-full shadow-lg uppercase tracking-wider border-2 border-white whitespace-nowrap z-20 flex items-center gap-1">
                            <CrownLogo className="w-3 h-3" /> PRIME
                        </div>
                    </div>
                    <div className="text-center">
                        <h2 className="text-amber-600 dark:text-amber-500 uppercase tracking-[0.2em] text-[10px] md:text-xs font-bold mb-1">Genetic Potential</h2>
                        <div className="text-5xl md:text-7xl font-black tracking-tighter text-transparent bg-clip-text bg-gradient-to-b from-amber-300 to-amber-600">{analysis.potentialScore}</div>
                    </div>
                </div>
            </div>

            <div className="max-w-3xl mx-auto text-center relative">
                <p className="text-lg md:text-xl text-gray-700 dark:text-zinc-300 leading-relaxed font-medium">{analysis.summary}</p>
                <div className="mt-6 flex flex-wrap justify-center gap-4">
                    <Button onClick={onRetake} variant="secondary" className="text-xs md:text-sm py-2 px-6">New Submission</Button>
                </div>
            </div>
        </div>
      </div>

      {/* Royal Starter Kit */}
      <div className="bg-gradient-to-r from-blue-900/20 to-zinc-900 border border-blue-500/20 p-6 rounded-3xl relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10"><CrownLogo className="w-48 h-48 text-white" /></div>
        <div className="relative z-10">
            <h3 className="text-lg font-black text-white uppercase tracking-tight mb-4 flex items-center gap-2">
                <span className="text-blue-500">///</span> ROYAL STARTER KIT
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-3">
                {starterKit.map((prod, i) => (
                    <a key={i} href={getAmazonLink(prod.searchQuery)} target="_blank" rel="noopener noreferrer" className="bg-black/40 border border-white/10 p-3 rounded-xl flex flex-col justify-between hover:bg-blue-600/20 hover:border-blue-500/50 transition-all group">
                         <div className="flex flex-col mb-2">
                            <span className="text-[10px] text-blue-400 uppercase font-bold tracking-wider mb-1">{prod.tag || 'ESSENTIAL'}</span>
                            <span className="text-xs md:text-sm font-bold text-white group-hover:text-blue-300 line-clamp-2">{prod.name}</span>
                         </div>
                         <div className="bg-white text-black px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest group-hover:bg-blue-500 group-hover:text-white transition-colors text-center mt-auto">
                            ACQUIRE
                         </div>
                    </a>
                ))}
            </div>
        </div>
      </div>

       {/* Subscription Upsell Card */}
       <div className="bg-gradient-to-br from-amber-600 to-amber-800 rounded-3xl p-1 shadow-2xl relative overflow-hidden group cursor-pointer hover:scale-[1.01] transition-transform" onClick={onOpenCoach}>
            <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-30"></div>
            <div className="bg-black/90 rounded-[22px] p-6 relative z-10 h-full flex flex-col md:flex-row items-center gap-6">
                <div className="flex-shrink-0 p-4 bg-amber-500/10 rounded-full border border-amber-500/30 animate-pulse-slow">
                    <CrownLogo className="w-12 h-12 text-amber-500" />
                </div>
                <div className="flex-grow text-center md:text-left">
                     <h3 className="text-xl font-black text-white uppercase italic tracking-wider mb-2">
                        Execution Is Everything
                     </h3>
                     <p className="text-zinc-400 text-sm mb-4">
                        Don't let this analysis go to waste. Get your personalized 
                        <span className="text-amber-500 font-bold"> Daily Action Plan</span>. 
                        Mewing reminders, skin cycling, and habit tracking.
                     </p>
                     <div className="flex flex-wrap gap-2 justify-center md:justify-start">
                         <span className="px-2 py-1 bg-zinc-800 text-zinc-300 text-[10px] uppercase font-bold rounded border border-zinc-700">Habit Tracker</span>
                         <span className="px-2 py-1 bg-zinc-800 text-zinc-300 text-[10px] uppercase font-bold rounded border border-zinc-700">Daily Schedule</span>
                         <span className="px-2 py-1 bg-zinc-800 text-zinc-300 text-[10px] uppercase font-bold rounded border border-zinc-700">Accountability</span>
                     </div>
                </div>
                <div className="flex-shrink-0">
                    <Button onClick={(e) => { e.stopPropagation(); onOpenCoach(); }} className="whitespace-nowrap bg-amber-500 hover:bg-amber-400 text-black border-none shadow-[0_0_20px_rgba(245,158,11,0.3)]">
                        Start Protocol ($29.99/mo)
                    </Button>
                </div>
            </div>
        </div>

      {/* Optimal Architect Section */}
      <ArchetypeVisualizer 
        activeArchetype={activeArchetype}
        isPremiumUnlocked={isPremiumUnlocked}
        isGenerating={isGenerating}
        currentImage={optimalImages[activeArchetype]}
        onGenerate={handleGenerateOptimal}
        onTriggerPaywall={triggerPaywall}
        onFullScreen={setFullScreenImage}
        loadingMessage={LOADING_MESSAGES[loadingMessageIdx]}
      />

      {/* Style Vision Board */}
      <div className="bg-white dark:bg-zinc-900 p-6 md:p-8 rounded-3xl border border-gray-200 dark:border-zinc-800 shadow-xl relative overflow-hidden">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-black text-gray-900 dark:text-white tracking-tight">STYLE VISION BOARD</h3>
            {!isPremiumUnlocked ? (
                <span className="bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400 text-[10px] font-bold px-2 py-1 rounded uppercase tracking-wider border border-amber-200 dark:border-amber-800 flex items-center gap-1">
                    <LockIcon className="w-3 h-3" /> Locked
                </span>
            ) : (
                <div className="flex items-center gap-2">
                     <span className="text-xs text-zinc-500">Custom Photo?</span>
                     <button onClick={() => styleUploadRef.current?.click()} className="p-1.5 bg-zinc-100 dark:bg-zinc-800 rounded-full hover:text-amber-500">
                         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z" />
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z" />
                        </svg>
                     </button>
                     <input type="file" ref={styleUploadRef} className="hidden" accept="image/*" onChange={(e) => handleSectionUpload(e, setCustomStyleImage)} />
                </div>
            )}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {(['hair', 'fashion', 'grooming'] as const).map(cat => (
                  <div key={cat} className="relative aspect-[3/4] bg-gray-100 dark:bg-black rounded-2xl overflow-hidden group border border-gray-200 dark:border-zinc-800">
                      {!isPremiumUnlocked ? (
                         <div className="absolute inset-0 cursor-pointer flex flex-col items-center justify-center bg-black/60 backdrop-blur-md z-20 text-center p-4 hover:bg-black/70 transition-colors" onClick={triggerPaywall}>
                              <div className="p-3 bg-zinc-800/80 rounded-full mb-3">
                                <LockIcon className="w-6 h-6 text-amber-500" />
                              </div>
                              <span className="text-white font-bold uppercase text-xs tracking-wider">Unlock {cat}</span>
                         </div>
                      ) : (
                         <>
                            {styleImages[cat] ? (
                                <img 
                                    src={styleImages[cat]} 
                                    className="w-full h-full object-cover cursor-zoom-in"
                                    onClick={() => setFullScreenImage(styleImages[cat])}
                                />
                            ) : (
                                <div className="absolute inset-0 flex items-center justify-center p-4">
                                    <Button onClick={() => handleGenerateStyle(cat)} variant="outline" className="text-xs" disabled={loadingStyle !== null}>
                                        {loadingStyle === cat ? 'Generating...' : customStyleImage ? `Visualize ${cat} (Custom Photo)` : `Visualize ${cat}`}
                                    </Button>
                                </div>
                            )}
                         </>
                      )}
                  </div>
              ))}
          </div>
      </div>

      {/* Hardmaxxing Section */}
      {analysis.hardmaxxing && analysis.hardmaxxing.length > 0 && (
          <div className="bg-zinc-900 rounded-[2rem] overflow-hidden shadow-2xl border border-zinc-800 p-6 md:p-8 mt-6 relative">
               {!isPremiumUnlocked && (
                   <div className="absolute inset-0 z-30 backdrop-blur-xl bg-black/40 flex flex-col items-center justify-center text-center p-6 cursor-pointer hover:bg-black/50 transition-colors" onClick={triggerPaywall}>
                        <div className="w-20 h-20 bg-zinc-800/80 rounded-full flex items-center justify-center border-2 border-amber-500 mb-6 shadow-[0_0_30px_rgba(245,158,11,0.3)]">
                            <LockIcon className="w-8 h-8 text-white" />
                        </div>
                        <h2 className="text-3xl font-black text-white uppercase mb-2">Surgical Protocol Locked</h2>
                        <p className="text-zinc-400 mb-8 max-w-md">Access advanced medical simulations, cost estimates, and risk analysis.</p>
                        <Button className="px-12 py-4 text-lg bg-amber-500 text-black hover:bg-amber-400 shadow-[0_0_20px_rgba(245,158,11,0.5)]">Unlock Hardmaxxing - $17.99</Button>
                   </div>
               )}

               <div className={`transition-all duration-500 ${!isPremiumUnlocked ? 'blur-xl opacity-30 pointer-events-none' : ''}`}>
                   <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
                      <div>
                          <h3 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
                              <span className="text-red-500">///</span> SURGICAL INTERVENTION
                          </h3>
                          <p className="text-zinc-400 text-sm">Advanced clinical reconstruction.</p>
                      </div>
                      
                      {isPremiumUnlocked && (
                          <div className="flex items-center gap-2">
                                <span className="text-xs text-zinc-500">Upload Clinical Photo?</span>
                                <button onClick={() => surgeryUploadRef.current?.click()} className="p-1.5 bg-zinc-800 rounded-full hover:text-red-500 border border-zinc-700">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                                        <path strokeLinecap="round" strokeLinejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z" />
                                    </svg>
                                </button>
                                <input type="file" ref={surgeryUploadRef} className="hidden" accept="image/*" onChange={(e) => handleSectionUpload(e, setCustomSurgeryImage)} />
                           </div>
                      )}
                   </div>
                   
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {analysis.hardmaxxing.map((proc, idx) => (
                          <div key={idx} className="bg-black border border-zinc-800 rounded-2xl overflow-hidden flex flex-col group">
                              <div className="relative aspect-[16/9] bg-zinc-800/50 overflow-hidden border-b border-zinc-800">
                                    {procedureImages[proc.name] ? (
                                        <>
                                            <img 
                                                src={toggledProcedures[proc.name] ? procedureImages[proc.name] : (customSurgeryImage || imageData || procedureImages[proc.name])} 
                                                className="w-full h-full object-cover"
                                            />
                                            <div className="absolute bottom-2 right-2 flex gap-2">
                                                <button onClick={() => toggleProcedureView(proc.name)} className="bg-black/50 text-white text-[10px] px-3 py-2 rounded-lg font-bold uppercase backdrop-blur-sm border border-white/20">
                                                    {toggledProcedures[proc.name] ? "Show Original" : "Show Result"}
                                                </button>
                                                <button onClick={() => imageData && procedureImages[proc.name] && setComparisonModal({ before: imageData, after: procedureImages[proc.name] })} className="bg-blue-600 text-white p-2 rounded-lg backdrop-blur-sm">
                                                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" /></svg>
                                                </button>
                                            </div>
                                        </>
                                    ) : (
                                        <div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center">
                                            {loadingProcedure === proc.name ? (
                                                <span className="text-[10px] text-zinc-400 animate-pulse font-mono">{LOADING_MESSAGES[loadingMessageIdx]}</span>
                                            ) : (
                                                <Button onClick={() => handleGenerateProcedure(proc.name, proc.description)} variant="secondary" className="text-xs py-2 h-auto">
                                                    Generate Outcome
                                                </Button>
                                            )}
                                        </div>
                                    )}
                              </div>
                              <div className="p-5 flex flex-col gap-4 flex-grow">
                                  <div className="flex justify-between items-start">
                                      <div><h4 className="text-lg font-bold text-white">{proc.name}</h4><span className="text-xs text-zinc-500 uppercase">{proc.type}</span></div>
                                      <div className="text-right"><div className="text-sm font-bold text-white">{proc.costEstimate}</div></div>
                                  </div>
                                  <p className="text-xs text-zinc-300">{proc.description}</p>
                              </div>
                          </div>
                      ))}
                   </div>
               </div>
          </div>
      )}

      {/* Detailed Analysis & Products (Free but below) */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 mt-4">
        {/* Skin */}
        <div className="space-y-6">
            <div className="bg-white dark:bg-zinc-900 p-6 rounded-3xl border border-gray-200 dark:border-zinc-800 shadow-sm">
                <div className="flex justify-between items-center mb-4"><h3 className="font-bold text-gray-900 dark:text-white">Skin Vitality</h3><span className={`text-xl font-black ${getScoreColor(analysis.skinAnalysis.score)}`}>{analysis.skinAnalysis.score}/10</span></div>
                <div className="space-y-2">
                    {analysis.skinAnalysis.products.map((prod, i) => (
                        <a key={i} href={getAmazonLink(prod.searchQuery)} target="_blank" rel="noopener noreferrer" className="block p-3 bg-gray-50 dark:bg-zinc-800 rounded-xl hover:bg-blue-50 dark:hover:bg-zinc-700 transition-colors group">
                            <div className="flex justify-between items-center"><span className="font-bold text-sm text-gray-900 dark:text-white group-hover:text-blue-600">{prod.name}</span></div>
                            <button className="w-full mt-2 py-1.5 text-[10px] font-bold uppercase tracking-widest bg-blue-600 text-white rounded-lg hover:bg-blue-700">ACQUIRE</button>
                        </a>
                    ))}
                </div>
            </div>
        </div>
        {/* Eyes */}
        <div className="space-y-6">
            <div className="bg-white dark:bg-zinc-900 p-6 rounded-3xl border border-gray-200 dark:border-zinc-800 shadow-sm">
                <div className="flex justify-between items-center mb-4"><h3 className="font-bold text-gray-900 dark:text-white">Eye Dominance</h3><span className={`text-xl font-black ${getScoreColor(analysis.eyeAnalysis.score)}`}>{analysis.eyeAnalysis.score}/10</span></div>
                <div className="space-y-2">
                    {analysis.eyeAnalysis.products.map((prod, i) => (
                        <a key={i} href={getAmazonLink(prod.searchQuery)} target="_blank" rel="noopener noreferrer" className="block p-3 bg-gray-50 dark:bg-zinc-800 rounded-xl hover:bg-blue-50 dark:hover:bg-zinc-700 transition-colors group">
                            <div className="flex justify-between items-center"><span className="font-bold text-sm text-gray-900 dark:text-white group-hover:text-blue-600">{prod.name}</span></div>
                            <button className="w-full mt-2 py-1.5 text-[10px] font-bold uppercase tracking-widest bg-blue-600 text-white rounded-lg hover:bg-blue-700">ACQUIRE</button>
                        </a>
                    ))}
                </div>
            </div>
        </div>
        {/* Hair */}
        <div className="space-y-6">
            <div className="bg-white dark:bg-zinc-900 p-6 rounded-3xl border border-gray-200 dark:border-zinc-800 shadow-sm">
                <div className="flex justify-between items-center mb-4"><h3 className="font-bold text-gray-900 dark:text-white">Hair Quality</h3><span className={`text-xl font-black ${getScoreColor(analysis.hairAnalysis.score)}`}>{analysis.hairAnalysis.score}/10</span></div>
                <div className="space-y-2">
                    {analysis.hairAnalysis.products.map((prod, i) => (
                        <a key={i} href={getAmazonLink(prod.searchQuery)} target="_blank" rel="noopener noreferrer" className="block p-3 bg-gray-50 dark:bg-zinc-800 rounded-xl hover:bg-blue-50 dark:hover:bg-zinc-700 transition-colors group">
                            <div className="flex justify-between items-center"><span className="font-bold text-sm text-gray-900 dark:text-white group-hover:text-blue-600">{prod.name}</span></div>
                            <button className="w-full mt-2 py-1.5 text-[10px] font-bold uppercase tracking-widest bg-blue-600 text-white rounded-lg hover:bg-blue-700">ACQUIRE</button>
                        </a>
                    ))}
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};
