import React, { useState, useEffect, useRef } from 'react';
import { LooksAnalysis } from '../types';
import { Button } from './Button';
import { CrownLogo } from './CrownLogo';
import { LOADING_MESSAGES } from '../utils/analysisUtils';
import { useUser } from '../contexts/UserContext';
import { useAIGeneration } from '../hooks/useAIGeneration';
import { getHistory } from '../services/historyService';
import { STRIPE_LINKS, PRICING } from '../config';
import { SEOHead } from './SEOHead';

// Components
import { PaywallModal, TopUpModal } from './PremiumModals';
import { ArchetypeVisualizer } from './ArchetypeVisualizer';
import { AnalysisHeader } from './analysis/AnalysisHeader';
import { AnalysisGrid } from './analysis/AnalysisGrid';
import { HardmaxxingSection } from './analysis/HardmaxxingSection';
import { StarterKit } from './analysis/StarterKit';
import { StyleVisionBoard } from './analysis/StyleVisionBoard';
import { ImageViewer } from './ui/ImageViewer';

interface AnalysisResultProps {
  analysis: LooksAnalysis;
  imageData: string | null;
  onRetake: () => void;
  scanId?: string;
  onOpenCoach: () => void;
}

export const AnalysisResult: React.FC<AnalysisResultProps> = ({ analysis, imageData, onRetake, scanId, onOpenCoach }) => {
  const { user, unlockPremium, addCredits, checkQuota } = useUser();
  const { generateAsset, isGenerating, activeOperation } = useAIGeneration(scanId);

  // --- UI State ---
  const [showPaywall, setShowPaywall] = useState(false);
  const [showTopUp, setShowTopUp] = useState(false);
  const [processingPayment, setProcessingPayment] = useState(false);
  const [loadingMessageIdx, setLoadingMessageIdx] = useState(0);
  const [fullScreenImage, setFullScreenImage] = useState<string | null>(null);

  // --- Asset State ---
  const [optimalImages, setOptimalImages] = useState<{ [key: string]: string }>({});
  const [styleImages, setStyleImages] = useState<{ [key: string]: string }>({});
  const [procedureImages, setProcedureImages] = useState<{ [key: string]: string }>({});
  
  // --- Feature State ---
  const [activeArchetype, setActiveArchetype] = useState<'prime' | 'titan' | 'icon'>('prime');
  const [toggledProcedures, setToggledProcedures] = useState<{ [key: string]: boolean }>({}); 
  const [comparisonModal, setComparisonModal] = useState<{ before: string, after: string } | null>(null);

  // --- Custom Uploads ---
  const [customStyleImage, setCustomStyleImage] = useState<string | null>(null);
  const [customSurgeryImage, setCustomSurgeryImage] = useState<string | null>(null);

  const hasAutoGeneratedRef = useRef(false);

  // 1. Rehydrate Assets from History
  useEffect(() => {
    if (scanId) {
        const history = getHistory();
        const item = history.find(h => h.id === scanId);
        if (item && item.assets) {
            const newOptimal: any = {};
            const newStyle: any = {};
            const newProcs: any = {};
            Object.keys(item.assets).forEach(key => {
                if (key.startsWith('optimal_')) newOptimal[key.replace('optimal_', '')] = item.assets![key];
                if (key.startsWith('style_')) newStyle[key.replace('style_', '')] = item.assets![key];
                if (key.startsWith('proc_')) newProcs[key.replace('proc_', '')] = item.assets![key];
            });
            setOptimalImages(prev => ({...prev, ...newOptimal}));
            setStyleImages(prev => ({...prev, ...newStyle}));
            setProcedureImages(prev => ({...prev, ...newProcs}));
        }
    }
  }, [scanId]);

  // 2. Cycling Loading Messages
  useEffect(() => {
      let interval: any;
      if (isGenerating) {
          interval = setInterval(() => setLoadingMessageIdx(p => (p + 1) % LOADING_MESSAGES.length), 1500);
      } else {
          setLoadingMessageIdx(0);
      }
      return () => clearInterval(interval);
  }, [isGenerating]);

  // 3. Auto-Generate Prime Archetype
  useEffect(() => {
    if (imageData && !optimalImages['prime'] && !isGenerating && !hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        handleGenerateOptimal('prime');
    }
  }, [imageData]); 

  // --- Handlers ---

  const handleSimulatePayment = (type: 'premium' | 'credits') => {
      setProcessingPayment(true);
      
      // Facebook Pixel: InitiateCheckout
      if (typeof window !== 'undefined' && (window as any).fbq) {
          (window as any).fbq('track', 'InitiateCheckout', { 
              content_name: type === 'premium' ? 'Premium Unlock' : 'Credits TopUp',
              value: type === 'premium' ? PRICING.PREMIUM_LIFETIME : PRICING.CREDIT_PACK_PRICE,
              currency: 'USD'
          });
      }

      const url = type === 'premium' ? STRIPE_LINKS.PREMIUM_UNLOCK : STRIPE_LINKS.CREDITS_TOPUP;
      window.open(url, '_blank');
      setTimeout(() => {
          if (type === 'premium') { unlockPremium(); setShowPaywall(false); } 
          else { addCredits(PRICING.CREDIT_PACK_AMOUNT); setShowTopUp(false); }
          setProcessingPayment(false);
      }, 8000);
  };

  const handleCustomUpload = (e: React.ChangeEvent<HTMLInputElement>, setFunc: (s: string) => void) => {
      const file = e.target.files?.[0];
      if (file) {
          const reader = new FileReader();
          reader.onload = (ev) => ev.target?.result && setFunc(ev.target.result as string);
          reader.readAsDataURL(file);
      }
  }

  const checkAccess = (key: string): boolean => {
      const status = checkQuota(key);
      if (!status.allowed) {
          if (status.reason === 'premium_lock') setShowPaywall(true);
          else setShowTopUp(true);
          return false;
      }
      return true;
  };

  const handleGenerateOptimal = async (archetype: 'prime' | 'titan' | 'icon') => {
    if (!imageData) return;
    setActiveArchetype(archetype);
    if (optimalImages[archetype]) return;

    if (!checkAccess(archetype === 'icon' ? 'icon' : 'optimal')) return;

    const img = await generateAsset('optimal', archetype, imageData);
    if (img) setOptimalImages(prev => ({ ...prev, [archetype]: img }));
  };

  const handleGenerateStyle = async (category: 'hair' | 'fashion' | 'grooming') => {
      if (styleImages[category]) return;
      const source = customStyleImage || imageData;
      if (!source) return;

      if (!checkAccess('style')) return;

      const img = await generateAsset('style', category, source);
      if (img) setStyleImages(prev => ({...prev, [category]: img}));
  };

  const handleGenerateProcedure = async (procName: string, description: string) => {
    const source = customSurgeryImage || imageData;
    if (!source) return;

    if (!checkAccess('surgery')) return;

    const img = await generateAsset('surgery', procName, source, { description });
    if (img) setProcedureImages(prev => ({...prev, [procName]: img}));
  };

  // --- Derived Data ---

  const starterProducts = [
    ...(analysis.skinAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'SKIN'}))),
    ...(analysis.hairAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'HAIR'}))),
    ...(analysis.eyeAnalysis.products.slice(0, 1).map(p => ({...p, tag: 'EYES'}))),
    ...(analysis.hardmaxxing && analysis.hardmaxxing.length > 0 ? [{ name: "Mastic Gum", reason: "For Jawline", searchQuery: "Mastic Gum", tag: "JAW" }] : []),
  ].slice(0, 6);

  const isPremiumUnlocked = user?.isPremium || false;

  return (
    <div className="w-full max-w-7xl mx-auto flex flex-col gap-6 animate-fade-in pb-20 px-4 sm:px-6 lg:px-8">
      <SEOHead 
        title={`Your AI Face Analysis Score: ${analysis.overallScore}/10`} 
        description={`My facial aesthetic score is ${analysis.overallScore}.`}
      />

      {/* --- MODALS --- */}
      {showPaywall && <PaywallModal onClose={() => setShowPaywall(false)} onPurchase={() => handleSimulatePayment('premium')} isProcessing={processingPayment} />}
      {showTopUp && <TopUpModal onClose={() => setShowTopUp(false)} onPurchase={() => handleSimulatePayment('credits')} isProcessing={processingPayment} />}
      
      <ImageViewer src={fullScreenImage} onClose={() => setFullScreenImage(null)} />

      {comparisonModal && (
          <div className="fixed inset-0 z-[70] bg-black/95 flex flex-col items-center justify-center p-2 md:p-8 animate-fade-in">
               <div className="w-full max-w-6xl h-full flex flex-col">
                  <div className="flex justify-between items-center mb-4 px-2">
                       <h3 className="text-white font-bold text-lg uppercase tracking-widest">Comparison</h3>
                       <button onClick={() => setComparisonModal(null)} className="bg-zinc-800 text-white px-4 py-2 rounded-full font-bold text-sm">Close</button>
                  </div>
                  <div className="flex-grow flex flex-col md:flex-row gap-2 md:gap-4 h-[80vh]">
                      <div className="flex-1 relative rounded-xl overflow-hidden"><img src={comparisonModal.before} className="w-full h-full object-cover" alt="Before" /><div className="absolute top-4 left-4 bg-black/70 text-white px-3 py-1 rounded text-xs font-bold uppercase">Before</div></div>
                      <div className="flex-1 relative rounded-xl overflow-hidden"><img src={comparisonModal.after} className="w-full h-full object-cover" alt="After" /><div className="absolute top-4 left-4 bg-emerald-600/90 text-white px-3 py-1 rounded text-xs font-bold uppercase">Simulation</div></div>
                  </div>
              </div>
          </div>
      )}

      {/* --- CONTENT --- */}

      <AnalysisHeader 
        analysis={analysis} 
        imageData={imageData} 
        optimalImage={optimalImages['prime']} 
        onRetake={onRetake} 
        onFullScreen={setFullScreenImage}
      />

      <StarterKit products={starterProducts} />

       <div className="bg-gradient-to-br from-amber-600 to-amber-800 rounded-3xl p-6 shadow-2xl relative overflow-hidden cursor-pointer flex flex-col md:flex-row items-center gap-6 group hover:scale-[1.01] transition-transform" onClick={onOpenCoach}>
             <div className="flex-shrink-0 p-4 bg-amber-500/10 rounded-full border border-amber-500/30 group-hover:bg-amber-500/20 transition-colors"><CrownLogo className="w-12 h-12 text-amber-500" /></div>
             <div className="flex-grow text-center md:text-left"><h3 className="text-xl font-black text-white uppercase italic">Execution Is Everything</h3><p className="text-zinc-200 text-sm">Get your personalized Daily Action Plan.</p></div>
             <Button onClick={(e) => { e.stopPropagation(); onOpenCoach(); }} className="bg-amber-500 text-black border-none">Start Protocol</Button>
        </div>

      <ArchetypeVisualizer 
        activeArchetype={activeArchetype}
        isPremiumUnlocked={isPremiumUnlocked}
        isGenerating={isGenerating && ['prime', 'titan', 'icon'].includes(activeOperation || '')}
        currentImage={optimalImages[activeArchetype]}
        onGenerate={handleGenerateOptimal}
        onTriggerPaywall={() => setShowPaywall(true)}
        onFullScreen={setFullScreenImage}
        loadingMessage={LOADING_MESSAGES[loadingMessageIdx]}
      />

      <StyleVisionBoard 
        isPremiumUnlocked={isPremiumUnlocked}
        styleImages={styleImages}
        isGenerating={isGenerating}
        activeOperation={activeOperation}
        onGenerate={handleGenerateStyle}
        onTriggerPaywall={() => setShowPaywall(true)}
        onFullScreen={setFullScreenImage}
        onUpload={(e) => handleCustomUpload(e, setCustomStyleImage)}
      />

      <HardmaxxingSection 
        analysis={analysis} 
        isPremiumUnlocked={isPremiumUnlocked} 
        onUnlock={() => setShowPaywall(true)}
        onGenerate={handleGenerateProcedure}
        procedureImages={procedureImages}
        loadingProcedure={isGenerating && !['prime','titan','icon','hair','fashion','grooming'].includes(activeOperation || '') ? activeOperation : null}
        toggleView={(name) => setToggledProcedures(prev => ({ ...prev, [name]: !prev[name] }))}
        toggledState={toggledProcedures}
        onCompare={(after) => imageData && setComparisonModal({ before: imageData, after })}
        imageData={imageData}
        customImage={customSurgeryImage}
        onUpload={(e) => handleCustomUpload(e, setCustomSurgeryImage)}
      />

      <AnalysisGrid analysis={analysis} />
    </div>
  );
};