import React from 'react';
import { Layout } from './Layout';
import { CrownLogo } from './CrownLogo';
import { APP_NAME } from '../config';

interface TermsOfServiceProps {
    onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
    return (
        <div className="min-h-screen bg-black text-white p-6 md:p-12 overflow-y-auto">
            <div className="max-w-3xl mx-auto">
                <div className="flex items-center gap-4 mb-8">
                    <button
                        onClick={onBack}
                        aria-label="Go back"
                        className="w-10 h-10 flex items-center justify-center rounded-full bg-white/5 hover:bg-white/10 transition-colors"
                    >
                        <svg className="w-5 h-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                    </button>
                    <CrownLogo />
                </div>

                <div className="prose prose-invert prose-amber max-w-none">
                    <h1 className="text-4xl font-black mb-8">Terms of Service</h1>
                    <p className="text-zinc-400 text-sm mb-8">Last Updated: January 27, 2026</p>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
                        <p className="text-zinc-300">
                            By accessing and using {APP_NAME}, you accept and agree to be bound by the terms and provision of this agreement.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold mb-4">2. AI Analysis Disclaimer</h2>
                        <p className="text-zinc-300">
                            Our service uses Artificial Intelligence to provide aesthetic analysis. By using the service, you acknowledge that:
                        </p>
                        <ul className="list-disc pl-5 text-zinc-300 space-y-2 mt-2">
                            <li>The results are generated by AI and are for entertainment and informational purposes only.</li>
                            <li>The analysis should not be considered as medical advice.</li>
                            <li>We are not responsible for any decisions made based on these results.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold mb-4">3. User Conduct</h2>
                        <p className="text-zinc-300">
                            You agree not to upload photos of others without their consent. Currently, our service limits scans to ensure fair usage of AI resources.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold mb-4">4. Purchases & Refunds</h2>
                        <p className="text-zinc-300">
                            <strong>Subscriptions:</strong> Premium subscriptions are billed monthly. You can cancel at any time.<br />
                            <strong>Refunds:</strong> We offer a 14-day money-back guarantee if you are not satisfied with the premium features.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold mb-4">5. Limitation of Liability</h2>
                        <p className="text-zinc-300">
                            In no event shall {APP_NAME} be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on our site.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};
